name: Go CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  go-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Go tidy
        run: go mod tidy

      - name: Go build
        run: go build ./...
